export const NAVIGATION = [
  "dashboard",
  "sirup-rup",
  "perencanaan",
  "verifikasi",
  "e-purchasing",
  "tender-non-tender",
  "kontrak-sp",
  "realisasi-belanja",
  "risiko-mitigasi",
  "audit-readiness",
  "timeline",
  "vendor-pasar",
  "klinik-ukpbj",
  "dokumen-template",
  "laporan",
  "pengaturan",
] as const;
