ALTER TABLE `paket_pengadaan`
  MODIFY `status_paket` ENUM(
    'PERENCANAAN',
    'SIAP_DIPROSES',
    'PERSIAPAN_DOKUMEN',
    'PENJADWALAN',
    'PENGUMUMAN_UNDANGAN',
    'EVALUASI_KLARIFIKASI',
    'PEMILIHAN',
    'PEMENANG_DITETAPKAN',
    'KONTRAK',
    'SELESAI',
    'GAGAL',
    'BATAL',
    'TERLAMBAT'
  ) NOT NULL DEFAULT 'PERENCANAAN';
