ALTER TABLE "rencana_umum_pengadaan"
  ADD COLUMN IF NOT EXISTS "kontak_penyedia_katalog" VARCHAR(120),
  ADD COLUMN IF NOT EXISTS "email_penyedia_katalog" VARCHAR(180),
  ADD COLUMN IF NOT EXISTS "alamat_penyedia_katalog" TEXT,
  ADD COLUMN IF NOT EXISTS "link_produk_katalog" VARCHAR(255),
  ADD COLUMN IF NOT EXISTS "kategori_produk_katalog" VARCHAR(120),
  ADD COLUMN IF NOT EXISTS "harga_penawaran_katalog" DECIMAL(18, 2),
  ADD COLUMN IF NOT EXISTS "nomor_sppbj" VARCHAR(120),
  ADD COLUMN IF NOT EXISTS "tanggal_sppbj" VARCHAR(120),
  ADD COLUMN IF NOT EXISTS "status_surat_pesanan" VARCHAR(80),
  ADD COLUMN IF NOT EXISTS "nomor_spk_kontrak" VARCHAR(120),
  ADD COLUMN IF NOT EXISTS "tanggal_kontrak_ep" VARCHAR(120),
  ADD COLUMN IF NOT EXISTS "nomor_spmk" VARCHAR(120),
  ADD COLUMN IF NOT EXISTS "tanggal_spmk" VARCHAR(120),
  ADD COLUMN IF NOT EXISTS "status_pengiriman_ep" VARCHAR(80),
  ADD COLUMN IF NOT EXISTS "tanggal_rencana_kirim" VARCHAR(120),
  ADD COLUMN IF NOT EXISTS "tanggal_aktual_kirim" VARCHAR(120),
  ADD COLUMN IF NOT EXISTS "nomor_surat_jalan" VARCHAR(120),
  ADD COLUMN IF NOT EXISTS "status_uji_fungsi" VARCHAR(80),
  ADD COLUMN IF NOT EXISTS "nomor_ba_uji_fungsi" VARCHAR(120),
  ADD COLUMN IF NOT EXISTS "tanggal_uji_fungsi" VARCHAR(120),
  ADD COLUMN IF NOT EXISTS "status_pemeriksaan_ep" VARCHAR(80),
  ADD COLUMN IF NOT EXISTS "nomor_ba_pemeriksaan" VARCHAR(120),
  ADD COLUMN IF NOT EXISTS "tanggal_pemeriksaan" VARCHAR(120),
  ADD COLUMN IF NOT EXISTS "hasil_pemeriksaan" VARCHAR(80),
  ADD COLUMN IF NOT EXISTS "nomor_bast" VARCHAR(120),
  ADD COLUMN IF NOT EXISTS "tanggal_bast" VARCHAR(120),
  ADD COLUMN IF NOT EXISTS "status_dokumen_pembayaran" VARCHAR(80),
  ADD COLUMN IF NOT EXISTS "status_pembayaran_ep" VARCHAR(80),
  ADD COLUMN IF NOT EXISTS "nilai_pembayaran" DECIMAL(18, 2),
  ADD COLUMN IF NOT EXISTS "nomor_invoice" VARCHAR(120),
  ADD COLUMN IF NOT EXISTS "nomor_faktur" VARCHAR(120),
  ADD COLUMN IF NOT EXISTS "tanggal_pembayaran_ep" VARCHAR(120);
